### ISSUE TITLE
您好，请问你跑通这个模型了吗？效果如何？

### ISSUE THREAD

**Issue by 943fansi** [Yang-Qirui/DeepTime4Battery#1]

**Comment by Yang-Qirui** [comment]
目前这个模型我们虽然跑通了，但是在我们的问题上表现不佳。我们研究的方向是从一小段段序列预测后续的长序列，所以这个模型的效果我们也不能保证它的效果，应该还是与实际问题有关。

**Comment by 943fansi** [comment]
感谢您的回答。长序列预测可以试试informer模型。

**Comment by Yang-Qirui** [comment]
明白。谢谢您的建议
